### PR TITLE
This is really an incredible time for our Project

### PR DESCRIPTION
**Pull request by rvargas**

### CODE REVIEW

**Comment by rvargas** [comment]
I've changed `Nation`for `Project`. No problemo, right? Right?

**Comment by thewarpaint** [comment]
Sorry, even paraphrasing should be limited, this completely changes the quote. But try again, Trump has plenty of material!

**Comment by rvargas** [comment]
:(

**Comment by thewarpaint** [comment]
For example, just from his latest tweet: "Wow, such enthusiasm and energy. Something very big is happening." https://twitter.com/realDonaldTrump/status/1047673458241560576

**Pull request closed without merging**
